_demo:
    resource: "@SocieteApplicationMonBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /monbundle

formation_rest:
    type: rest
    prefix: /rest
    resource: "@SocieteApplicationMonBundle/Controller/FormationRestController.php"
